slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    odom_frame: odom
    base_frame: base_link
    map_frame: map
    scan_topic: scan
    max_laser_range: 8.0
    minimum_time_interval: 0.5
